### ISSUE TITLE
Review CSS `rem` unit

### ISSUE THREAD

**Issue by incinirate** [incinirate/ccDHAR#5]
In the current implementation, `rem` is treated differently than normal, instead of being treated as the proportional to the 'root' em value, it, misleadingly so, means 'REMaining space', so `50rem` means 50% of the remaining space in that direction. We need to think about if this is appropriate behavior.

The original reason for doing this was to provide a replacement for flexbox type functionality, as computing remaining space is not possible except via flexbox in normal css.

Possibly we could change `rem` to mean root em, and also create a new unit for remaining space, otherwise we could fully implement flexbox.

**Comment by Galaxtone** [comment]
I kind of was thinking this would be like HTML/CSS all the way, but this is kind of challenging that idea so I'm not sure... I mean it would be useful.

Maybe we could make it into something like `remaining: 50%;` in CSS.

So you could still do like `<tag style="remaining: 50%;"></tag>`

**Comment by incinirate** [comment]
Ehh, that wouldn't really work that well, as it needs to be applicable to many different properties, so adding a new unit would be the most applicable, something like `width: 25%rem` maybe?

**Comment by Galaxtone** [comment]
It'd prefer `remaining: 25%;` or at least `25% remaining` in place of a "unit" it would be easy to understand but I don't know if this abnormal to how HTML/CSS normally functions, but I think it's work better and we could add `rem` itself as to avoid confusion, so it'd be a win-win.

**Comment by incinirate** [comment]
The problem with doing `remaining: 25%` is that the styling engine wouldn't know which properties to apply that to. It has to be a special unit if we want this functionality. Alternatively, and in the long run, we should eventually properly implement flexbox.

**Comment by Galaxtone** [comment]
And we agree to use `remd` (e.g. `25remd`) to represent remaining space.

**Comment by Galaxtone** [comment]
Woops, my bad.

**Comment by incinirate** [comment]
All good. So formally speaking, we need to rename the reference to the remaining space operator to `remd` and implement `rem` as root em.

**Comment by Galaxtone** [comment]
Pull Request https://github.com/incinirate/ccDHAR/pull/11

I believe I have fixed this issue.

**Comment by incinirate** [comment]
Fixed in #11
