### ISSUE TITLE
`em` acts like `rem`

### ISSUE THREAD

**Issue by incinirate** [incinirate/ccDHAR#7]
The `em` unit for font sizes doesn't currently respect it's parent's values for font-size.

**Comment by incinirate** [comment]
Partially related to #5, and requires #6 to work properly, but we can implement the functionality css side before it has to actually work properly.

**Comment by Galaxtone** [comment]
I have fixed this problem excluding the functionality of #6, I feel that would require its own work while fixing #7.

Pull Request https://github.com/incinirate/ccDHAR/pull/11

**Comment by Galaxtone** [comment]
https://github.com/incinirate/ccDHAR/pull/11
